sudo: false
install: true
language: java
jdk: oraclejdk7

script:
  - ./gradlew clean build install

after_success:
  - test "$TRAVIS_TAG" == "" && test "$TRAVIS_REPO_SLUG" == "forerunnergames/fg-tools" && test "$TRAVIS_BRANCH" == "master" && test "$TRAVIS_PULL_REQUEST" == "false" && ./gradlew artifactoryPublish
  - test "$TRAVIS_TAG" != "" && test "$TRAVIS_REPO_SLUG" == "forerunnergames/fg-tools" && test "$TRAVIS_PULL_REQUEST" == "false" && ./gradlew bintrayUpload
  - ./gradlew jacocoRootReport coveralls

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - developers@forerunnergames.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: SAAia0vfj/N/6F8GHXoaoP4qOatzGCWZslT/e5icKlVnflis+IEWaiLwd+i4u073ONwLYsa/fnLW2rV8WFbA1q0MRXmiuxFHXLSQA9itg3FqjJ9xMpZMEwyuHXjI/LHks8efWRECz7goxfaW3Edyo/zNIE7n/yesBZmdfO8cxbHZQBo2MzlJd3yQtSV9nvm7Pm/YJdPQItUfWaQuBFFe0hq5laz5m1kBHzvGRqbtVPDtYREKvQ8cE0DMc/KC3iRclEZtQehpXuLCC1BN84AI4xVPY/hojaVs/+u+MZKkGvtL6qOoK0oWMHIfEuP12PadcT4OMgfXy1VmKPn19ns1D+wpi8U3hUPEe9UqgezVimDNfINh3/L6+mRNEQVOS+qoGpYv3M2cYzH36RhEHVRUa8Jg5yLi7KBEDMRbwGDzvLnFGba56DvmIeUIN4iyK0Q+G7tE7YvGHPPMJL54tTESAW1+1rKVO8EBU/VvjDvNBtNeH2mQDP0MIxAtYmJY+79A+8QftqRgVfXuihQEXU5xIQPPgsvllaH51y3TZmaVaN8cR4sSkQCFqsiWqnGmhGskQnuAZ2dpFubDG8/OpFkE/kYaARdq1RhfshRXYu9mrZsTIMwYJ2nKAhsRzBPs4wMXOp/YjbHONOTBgGlwUw3o/35FoQftoczGF7Y64O9RRDc=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html

env:
  global:
    - secure: RnNUTlm95mH9+jrl1sep70JUb8JJ/IxekNNyvH+MOZX3FctnS3yrGutO4f+uvwxTFTDSHG2QHmly4Zj9SQZO9RjaqWjzJdfdD/xVIZIFm+bGsTGXSoVW3QY1ygRnPffhrGQubEXqBRvRH8vXDbcow19+ARp5CqOFpkIgKVZjzGeQ/Zq8EuaO/joSD6xSH+felZR6mIKJdXuDYk7Sy805+Lv1zOU8/AW5RjKfZDAJVPGzjstr34XjdDXUG1S4uU9he6mMSvEIdLQNLM2HJJGIhgip47y1dTokhy40enDn4ExGmqAoRWN6fr+ICHio7tmfya7hpG/HI1gU7xMqUJQSV9lGTR0W9EUGsfxZJsRHYd/N17zBK6+uk1/q2vS9phWvgEULa9fhs+hKrldniiNvgNUa5DE4QELE7oM25ikPRHvY/eAF0aS84+YyCsMfaotMrnkMvmSrfelebRUmwp68r377FjCeIloRQGIvKpggD1U6/FDZwymg1F6I8vY9yoWw662Hd0cAERAEq0aVbaAlSaoijFsHwflZp2Zpf0Y7HnhCD1QQaYkLxy+SVXQ+u5qtRZ1TMPw9f9ATtlLKkVyKoFNlyP0DKs+cX2q8YRot7SK/fORnHbKG1m8FE+vWqSd5wX0hIb/J4vwcw6wDPkXi5O3PXewuC2B6bP6R7bnYgks=
    - secure: eyFFpHG53g6LCAxmHFp0eky/54kyZNGNfTCCUcR3gt665pZc3SE9gBqaEYK9yXXF8jxpqJhga/2rM8OGY/pbp36OpxbRt8yLFbF37JI7dtZ2wamfxJsCnkPKwHWny461JFuUTrt+eG0MwE/UaGoqe4RRnHDSGL0QyyWUO35UPxSS5iSNMQFq+dgBY6Yv+500vvZnRiRnteIiQ8hht3iUk9R0Eni1i8Ul+t9WJ6y/UEKCUB7zaJXMcDS7OOnHG5TNcJnmi2GV7Jsudaa8XI9dZHl5wQeTNShovImAoiE9KmVfRjE0EoT9kbfh+0jMyPE8ARfYdLg8hnDLeNtz5YqKFx0jpXar0DQRDFcQDw9RqcDkjDa6gWo12vnMA9ETSaCQwJtHRaxb1My/y86qB+xmwkLNKDbw6y31ocy6ZZi+2kONFtegPEbYHSbWA3aF+OnEjWQ0vz43law0UxBF6K1pYmVkROt0TSdkKyoHD4ZT4szz9CLbbU7MIvNWI5TBY8I/zgIsTKB4xS9hq2+1vQFJ8t71Idy0hbkG92PEnbhJACewfJFWnSAiDniXTixHrSlLoEExs+iKSEh0exiaNZjyj42g6phiw7tB04NUwSYmudGUXZ6tZF0Vts1M0KixKlOYpfOAjECPPZpe59srWkWUTG3/SW9P4/MmqHVOYqlobYo=
