sudo: false
install: true
language: java
jdk: oraclejdk7

script:
  - ./gradlew clean build install

after_success:
  - test $TRAVIS_REPO_SLUG == "forerunnergames/fg-tools" && test $TRAVIS_BRANCH == "develop" && test $TRAVIS_PULL_REQUEST == "false" && ./gradlew artifactoryPublish
  - test $TRAVIS_REPO_SLUG == "forerunnergames/fg-tools" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_PULL_REQUEST == "false" && ./gradlew bintrayUpload
  - ./gradlew jacocoRootReport coveralls

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - developers@forerunnergames.com
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: BF31y6SwqiY2mOFdOqBELTG95JN6MTEqw0unlquddmZoDYY46QMyIh5BQlTh+XUP/Pdc4FwR7RZKAQqWMp/U9T27b34XSemiflVD9Fbm3oF6tCUhLSnLzGAaZWngI8ojIyv3+GFw23+c4k7GoC34WAg3sVyNZbIXeJDZWpX4YAr9moNsNcS6279+tYGnu1VgzF4DU3fNCYg/QSZSyrLdZ4Hcf7SGIVibdggIfJvxytURYr7pouVUR0OF+Cu6NNlfiIeOWh5rHGMdGkAAG1/lxBsrnDY4piYtJ9jO5FAbp8UeIdRxNFqIGKt3Qn7TBp6mbIMlRFHUCPeZxK+zx2Qx5hMTPY/0P9v8DXNL+4FnF50Zwpae6+KhMTkAoDlxAGjuEgt1BbN7RKpCX4r97g6ULEmXxe48EouU8Xfr4HbuWyicV2P401Wd96ehUqy4FXaG/uCxA+r95o4zepGOUvsj77sdtNmPqPDpFSbhLdhCToWEj+tiIibDhDPjKigYbvBQ3v30diglk4/HbFcu5Tr4kDG7un8xT2aqiBkSBvspTJUk8eHtzlrYRxuo5hMUAn60kt1y4haSIkPzjMX6r8ujh2/rraZEh+8yJxURRSwFhoE2a3DD8J+xzAekHavyiG6wpWkaeRNLr8cOZyE39+KYFm3k/LZZfgErmIOyiT+8RRg=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'

env:
  global:
    - secure: m4txkYbU8jpWQ+fmsjcFBpu+qlEmkcmxtnpbbMUxgCXfMYovuoFJ6DxmUOovC20RQuciJuXOBWVQckmvUKi2j3zMuEjZTQnSFIRpdm6tyAqc+wjGeme3hA/n98SjAqy95/047EUYlDi0v3bVGYSa8BGSkt518M3X3YyBKpRVowc4ngI62fAUeW6MLzP2ircHn9d1UKRvq0P08MaiIh0zt0HwSO8Cmy03XCjD6+SHlWaxPI/2CD3pCfHwIR8zjfqQzRdnpjQ0dxou08HBMTVKJsjEM8TCR0CpfRC1RkzXmXAp9JUihK/d0kLHMEdrAyWxrTpURZTcK8Uge6twmNqsLR9H7hGeLrShjeJlpr1NJeKs2ElOxIylHQBuF7jxe3bAylVtAE85v51aAX+SEqQamjIvuyi+5vpED+sTjr0uqpKBzX1txQ7I4YjLSKUnSJtThL9B5uarSggLXocP0Q6k83D8WjRIoIYtqByIrtgvu2zMp0CjQBFlp7dgz71EB4mWAchBGZvZPgDd2e9rqxjBLurp44hsv0YQUIMqXx1VqXlQtulwb/UGPgnjHbibiG9AYVz5pHmz5ey95AursiIz0q9LewVwJX+JWjyxhFRiHiG0a5pNoF8uQ5k/kC835Q3SjJCqQetj4mGG4oVEvRgcGgxsM/aBsY3mlGua9LsQBAU=
    - secure: bnRmwaA5zMasIQU26hE8RcYINF2i+NrsVp3LyK7QAjTQo/34eWC77vMvaPhWO0Ohw4og+/UPjIXif7sdUugzvSDsvXHSdCBzCmrtzWl47Pqsyl3NNXPCPA98c1VIgmM66ahT0Orq3vJO/mhlkzXCBpUgi3Dot5PCm2CYtLKdTVnNS2GvTSCmP6FxEzGRp7Jddjc92Yk8QKDWpHS+wPlICH0Lv9o+klOf0QPp/whD2/R7uMPQw3+9rMQFLsOjuTDwJjfVUensCeiB0PwQ+ywGcLKFb1fkD6Ehu66guWyGD3WgzTO590M1ALNuWCnlotnq88oJZ5xSK4q1Q3rRp10fgLt7QA7fFesDi2DWs/F4dOVxMl993IS0F5XxrL4Gsn+WOCyZTe2vp7nvJ28gO+XblFcMb6ELj55WAKhNFPjp6Zrs7+xWGjqS8/Z2EG94J9ex/h0xtKyj6vhRRzP2SWkoe90HSfcLk75M+pzUJ1EOXSux/Cjuhx7vQP/NU+0GVXenYHhI0FULNFOIaTSJFqsf7wunloM5UQuPNKgckpfz2SAttmsS/7U1Ip6tSkXDfZ+fhQrALDEty+iGhYcn/h1OipOnHtLoy5ELjR2Xu7oAynYtFlnu9BUQLfJ+GhAnadOI3uA6zAWPpL8qp45h1SyqxXDS3XDsNu1emxfzpOysqv8=
