#
# Copyright © 2011 - 2013 Aaron Mahan
# Copyright © 2013 - 2016 Forerunner Games, LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

sudo: false
install: true
language: java
jdk: oraclejdk7

script:
  - ./gradlew clean build install

after_success:
  - test "$TRAVIS_TAG" == "" && test "$TRAVIS_REPO_SLUG" == "forerunnergames/fg-tools" && test "$TRAVIS_BRANCH" == "master" && test "$TRAVIS_PULL_REQUEST" == "false" && ./gradlew artifactoryPublish
  - test "$TRAVIS_TAG" != "" && test "$TRAVIS_REPO_SLUG" == "forerunnergames/fg-tools" && test "$TRAVIS_PULL_REQUEST" == "false" && ./gradlew bintrayUpload
  - ./gradlew jacocoRootReport coveralls
  - ./collect-build-artifacts.sh

after_failure:
  - ./collect-build-artifacts.sh

addons:
  artifacts:
    branch: master # FIXME: This is being ignored
    bucket: ci.forerunner.games
    target_paths: builds/fg-tools/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER
    paths: "build/collected"
    key:
      secure: NhJDmaau8R5goQbGOShL3M/IWsupUbj0CuQENkYXxg9DWHY6xeqNu6xy3AQlz5xmuak7lbWSzvEJ3qFuvBrMgQvUr3lZ2Tt0UaIg8tw2LLhLU1NnA/Q4dPEWUFEtfp2L5+7fIqqIpoiPkPc/s7+lzOZza6Q8PVVmeDm0i0LsWZSQ3AN2GX6y6FASUQ6ItblRzqFItamy+37TShCprL5mvEqemDwuYsyUW8LL37bK6Zb4lM5ZT2cTP0jME0rJY757Ng4e6TO7+uk4BOAkhr7BAVNBY/kc+DrKG8Xx1JwByxKWyxYWxdP0mqaD1AlOTPx4k7GjTTNwx5U9+qJwEKEP0NOH8c93QphQmilnTquJ5ZIP4Gg2UCgapEaPXUSSzpolaTsc8eXYcZ/0HvL7x6WfMmMcH7Gnjw4y+L4xaEDsC6JLzOJf4Pf7cP8lI+uoa6PHh2wDkOjNes1Mok9XLU/9gXh9vu0TBOhS2O67y6DeiaXRdaoYRtVo4Qr4xXD7/6k4eL4UnrSmh5b32WE7Phc/8Vgn5iaRkhcN8H4V/8CbQOT55xJ52XRwIEfdGl7lf4QyyOottkxjgFbA8ue7e2tfX2HS8KjscoNypRQw4RuV7Kbav59mvJZcO0bqbjAao12X7n8I5xCPz12iQNRTBOc9cRpme4XfOl9E33pBcg5ubsc=
    secret:
      secure: GmQHyRPq+LGX3MG7riHfsU/6jrrTn9VDbC5SnCoKJkE4bVuxohj54zpCcNbJtitLGKP3nRBZiAE+w53NYidKhIb6YFvZ297bXLWFp1LC4BWYUl9u8D1wNd7Z4TMpo9ilBLLeuZJbPlvQ57J5wTR+8SAeQ2cCDefFhe/sf3FGuzrlMJR4YUOUgtceNJdXJLOy3zCpSV156jq6sqB9nNrSsgaMb1ZTB+sa+ETcGRmheLA9kYLtph/UFgu0LvFgqKU1Kk7ny+4WdwHQnjeuhaVMZOgpXkgjDJV7aem2h6/yCeYrJNC+Fk/93qOm+9mfDZXUPH76EXM322Bd26mu1EuSpWj5aQeQCre3ZPRvcHodpGHqoL5rGnv38MvJ2bw8tsh2FiOvR0tkUTEPhsfpHQ/ccEXdmd4/ERgu/NBksl9LUjtyV6+EhOJFyBMUkar7BnUDTJAD1/qHN7iMEVE9115OLb7l9yFEmJDM4b9FtJa0r7WmOnsZmGMgjU0CXPF9xSeTg3P7bm06svKNmNnwIOO01lCLXVOcXdra6uuCoHAOArvnQSVTBS2sBGgEtHL8MSXQyu8OmX+FiKq/4wdu6LM/zZGrAqhqAToaSO6+NY1/ZrYRadQzJclrLXf000wKX4GAOUJCh0NDHMv/6bdfNVjm/UOcy5Fn+r/EP66kcf2slfI=

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - developers@forerunner.games
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    on_pull_requests: true
    secure: sTSPaCT8k1KHonGHGk1MdkJVlxCIY8JNQO/m0DhNHkKLzvbzgB8NPFp2AmaJHBZnzicabTDsTyT3XjkPQY28JWmQ8arFKk8XTLbOlm0hxV9eSIvbk1vxagg28MdzqCyf6058k+CY3KADSl2wiZHFAatgfvDxtTUUnITlYc45Sz3eEiIFol+6lBICMCfGGSTgf1E0mZ/e9Sv5XZUI+MtX4AVA/9c/5yxX/CykCJZcmDDjcreB8HpcVI7mEREBJZCyRjVS39yG9ykDDg9y8XnRcpKdyPVSEesxia4wWhS19LhNFsfUrdrIikcYMK+tPsGvwVE/js5CUlVmxfRzVWjJ+EPjaNhjaD86FrPv85FTf/1ZiUIG77oQPWQcrZUo60IGUZEsDybi9feZn4jbwWy/EVbo/3eVnawStPs+aijPlesRFoGZSRqHw4RMOmuVlUBH0JEoN7eBM9gyHtLUPrkRk9myuRHa36DYI4C4j9Tk+ZLwQ4OGYeNTykrkGrrNmmDSqPOuL76PDeo1DOOC9kjxhGOt8EbXNwR1rnRt8WjlF8mzozmlDrqP8IVoF3BrCceqJqBwdSMT7LaJYoIrFfLui6tKTYTJQgx4tjuIi/YqAQguKVPLgggBL5dOZUaD4lX6FqKjwqwl3UXBVirENjkW3hBK3Z53W3SIzXSW2DODnVM=

env:
  global:
    # Bintray credentials
    - secure: RnNUTlm95mH9+jrl1sep70JUb8JJ/IxekNNyvH+MOZX3FctnS3yrGutO4f+uvwxTFTDSHG2QHmly4Zj9SQZO9RjaqWjzJdfdD/xVIZIFm+bGsTGXSoVW3QY1ygRnPffhrGQubEXqBRvRH8vXDbcow19+ARp5CqOFpkIgKVZjzGeQ/Zq8EuaO/joSD6xSH+felZR6mIKJdXuDYk7Sy805+Lv1zOU8/AW5RjKfZDAJVPGzjstr34XjdDXUG1S4uU9he6mMSvEIdLQNLM2HJJGIhgip47y1dTokhy40enDn4ExGmqAoRWN6fr+ICHio7tmfya7hpG/HI1gU7xMqUJQSV9lGTR0W9EUGsfxZJsRHYd/N17zBK6+uk1/q2vS9phWvgEULa9fhs+hKrldniiNvgNUa5DE4QELE7oM25ikPRHvY/eAF0aS84+YyCsMfaotMrnkMvmSrfelebRUmwp68r377FjCeIloRQGIvKpggD1U6/FDZwymg1F6I8vY9yoWw662Hd0cAERAEq0aVbaAlSaoijFsHwflZp2Zpf0Y7HnhCD1QQaYkLxy+SVXQ+u5qtRZ1TMPw9f9ATtlLKkVyKoFNlyP0DKs+cX2q8YRot7SK/fORnHbKG1m8FE+vWqSd5wX0hIb/J4vwcw6wDPkXi5O3PXewuC2B6bP6R7bnYgks=
    - secure: eyFFpHG53g6LCAxmHFp0eky/54kyZNGNfTCCUcR3gt665pZc3SE9gBqaEYK9yXXF8jxpqJhga/2rM8OGY/pbp36OpxbRt8yLFbF37JI7dtZ2wamfxJsCnkPKwHWny461JFuUTrt+eG0MwE/UaGoqe4RRnHDSGL0QyyWUO35UPxSS5iSNMQFq+dgBY6Yv+500vvZnRiRnteIiQ8hht3iUk9R0Eni1i8Ul+t9WJ6y/UEKCUB7zaJXMcDS7OOnHG5TNcJnmi2GV7Jsudaa8XI9dZHl5wQeTNShovImAoiE9KmVfRjE0EoT9kbfh+0jMyPE8ARfYdLg8hnDLeNtz5YqKFx0jpXar0DQRDFcQDw9RqcDkjDa6gWo12vnMA9ETSaCQwJtHRaxb1My/y86qB+xmwkLNKDbw6y31ocy6ZZi+2kONFtegPEbYHSbWA3aF+OnEjWQ0vz43law0UxBF6K1pYmVkROt0TSdkKyoHD4ZT4szz9CLbbU7MIvNWI5TBY8I/zgIsTKB4xS9hq2+1vQFJ8t71Idy0hbkG92PEnbhJACewfJFWnSAiDniXTixHrSlLoEExs+iKSEh0exiaNZjyj42g6phiw7tB04NUwSYmudGUXZ6tZF0Vts1M0KixKlOYpfOAjECPPZpe59srWkWUTG3/SW9P4/MmqHVOYqlobYo=