package com.forerunnergames.tools.common.id;

import com.forerunnergames.tools.common.Classes;

import java.util.UUID;

/**
 * Provides a static interface for generating global, unique Id values. IdGen keeps and increments an AtomicInteger
 * 'tick' variable internally to guarantee that values returned by { @link #generateUniqueId() } are globally unique.
 */
public final class IdGenerator
{
  /**
   * Generates a globally unique Id value by fetching and incrementing a static, internal integer value.
   *
   * @return an Id guaranteed to be unique from others generated by this method.
   *
   * @throws IllegalStateException
   *           if the internal integer used for generating Id values exceeds Integer.MAX_VALUE.
   */
  public static Id generateUniqueId ()
  {
    return new Id (UUID.randomUUID ());
  }

  private IdGenerator ()
  {
    Classes.instantiationNotAllowed ();
  }
}
